# Generated by Django 4.2.1 on 2025-11-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='Class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
