# Generated by Django 4.2.1 on 2025-12-04 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_calendarevent_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='eventID',
        ),
    ]
