# Generated by Django 4.2.1 on 2025-12-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_calendarevent_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOffDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100)),
                ('time', models.TimeField()),
            ],
        ),
    ]
