# Generated by Django 4.2.1 on 2025-12-08 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_timeoffdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeaccherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=100)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.attendance')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schelude', models.CharField(max_length=100)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.attendance')),
            ],
        ),
    ]
