# Generated by Django 4.2.1 on 2025-12-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_teaccherattendance_studentattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaccherattendance',
            name='attendance',
        ),
        migrations.DeleteModel(
            name='StudentAttendance',
        ),
        migrations.DeleteModel(
            name='TeaccherAttendance',
        ),
    ]
