# Generated by Django 4.2.1 on 2025-12-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_remove_teaccherattendance_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='counter',
        ),
        migrations.AddField(
            model_name='attendance',
            name='shift',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
