# Generated by Django 4.2.1 on 2025-12-11 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_remove_attendance_counter_attendance_shift_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetail',
            name='user',
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
        migrations.DeleteModel(
            name='UnknownPerson',
        ),
        migrations.DeleteModel(
            name='EmployeeDetail',
        ),
    ]
