# Generated by Django 4.2.29 on 2026-04-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_remove_employeedetail_user_delete_leave_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.CharField(help_text='Vd: http://192.168.1.100:81/stream', max_length=255)),
                ('cam_type', models.CharField(choices=[('IN', 'Điểm danh VÀO'), ('OUT', 'Điểm danh RA')], default='IN', max_length=10)),
                ('status', models.BooleanField(default=False, help_text='Bật/Tắt stream')),
            ],
        ),
    ]
