# Generated by Django 4.2.29 on 2026-04-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_ipcamera'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipcamera',
            name='attendance_enabled',
            field=models.BooleanField(default=True, help_text='Bật/Tắt chức năng điểm danh'),
        ),
        migrations.AddField(
            model_name='ipcamera',
            name='tracking_enabled',
            field=models.BooleanField(default=True, help_text='Bật/Tắt chức năng phát hiện người lạ'),
        ),
    ]
