# Generated by Django 4.2.29 on 2026-04-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_ipcamera_attendance_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ip_address',
            field=models.CharField(blank=True, help_text='Địa chỉ IP của ESP32', max_length=50, null=True),
        ),
    ]
