# Generated by Django 4.2.1 on 2025-11-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0002_users_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
