# Generated by Django 4.2.1 on 2025-12-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0004_alter_users_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='roll',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Teacher', 'Teacher'), ('Student', 'Student')], default='Student', max_length=10),
        ),
    ]
